package com.github.ivigns.abbyy;

class Point {
    public Point(int x, int y) {
        this.x = x;
        this.y = y;
    }

    // my
    /*public boolean equals(Point other) {
        return x == other.x && y == other.y;
    }

    public int hashCode() {
        int xHash = x * 37 % 64;
        int yHash = y * 37 % 64;
        return xHash ^ yHash;
    }*/

    // autogenerated
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Point)) return false;

        Point point = (Point) o;

        if (x != point.x) return false;
        return y == point.y;
    }

    @Override
    public int hashCode() {
        int result = x;
        result = 31 * result + y;
        return result;
    }

    public int getX() {
        return x;
    }

    public void setX(int x) {
        this.x = x;
    }

    public int getY() {
        return y;
    }

    public void setY(int y) {
        this.y = y;
    }

    private int x;
    private int y;
}

public class Main {
    private static double distance(Point a, Point b) {
        int xDist = b.getX() - a.getX();
        int yDist = b.getY() - a.getY();
        return Math.sqrt(Math.pow(xDist, 2) + Math.pow(yDist, 2));
    }

    public static void main(String[] args) {
        Point a = new Point(2, 3);
        Point b = new Point(5, 7);
        System.out.println(distance(a, b));   // 5.0
    }
}
